//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usis.PushNotification.Administration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("usis.PushNotification.Administration.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup....
        /// </summary>
        internal static string ActionBackup {
            get {
                return ResourceManager.GetString("ActionBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Certificate.
        /// </summary>
        internal static string ActionDeleteCertificate {
            get {
                return ResourceManager.GetString("ActionDeleteCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Devices.
        /// </summary>
        internal static string ActionGoToDevices {
            get {
                return ResourceManager.GetString("ActionGoToDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the device list view of the selected channel..
        /// </summary>
        internal static string ActionGoToDevicesDescription {
            get {
                return ResourceManager.GetString("ActionGoToDevicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Certificate....
        /// </summary>
        internal static string ActionInstallCertificate {
            get {
                return ResourceManager.GetString("ActionInstallCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string ActionRestartService {
            get {
                return ResourceManager.GetString("ActionRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore....
        /// </summary>
        internal static string ActionRestore {
            get {
                return ResourceManager.GetString("ActionRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ActionStartService {
            get {
                return ResourceManager.GetString("ActionStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ActionStopService {
            get {
                return ResourceManager.GetString("ActionStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Certificate.
        /// </summary>
        internal static string ActionUninstallCertificate {
            get {
                return ResourceManager.GetString("ActionUninstallCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Certificate....
        /// </summary>
        internal static string ActionUploadCertificate {
            get {
                return ResourceManager.GetString("ActionUploadCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APNs.
        /// </summary>
        internal static string APNs {
            get {
                return ResourceManager.GetString("APNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed..
        /// </summary>
        internal static string BackupCompleted {
            get {
                return ResourceManager.GetString("BackupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usisPNRouter.Backup.zip.
        /// </summary>
        internal static string BackupFileName {
            get {
                return ResourceManager.GetString("BackupFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Archive (*.zip)|*.zip.
        /// </summary>
        internal static string BackupFilter {
            get {
                return ResourceManager.GetString("BackupFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string CertificateStateInstalled {
            get {
                return ResourceManager.GetString("CertificateStateInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string CertificateStateUploaded {
            get {
                return ResourceManager.GetString("CertificateStateUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The push notification channel &apos;{0} ({1})&apos; already exists..
        /// </summary>
        internal static string ChannelExists {
            get {
                return ResourceManager.GetString("ChannelExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string ChannelScopeNodeFormat {
            get {
                return ResourceManager.GetString("ChannelScopeNodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string ColumnAccount {
            get {
                return ResourceManager.GetString("ColumnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle ID.
        /// </summary>
        internal static string ColumnBundleID {
            get {
                return ResourceManager.GetString("ColumnBundleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string ColumnCertificate {
            get {
                return ResourceManager.GetString("ColumnCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColumnDescription {
            get {
                return ResourceManager.GetString("ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Token (hex).
        /// </summary>
        internal static string ColumnDeviceToken {
            get {
                return ResourceManager.GetString("ColumnDeviceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string ColumnEnvironment {
            get {
                return ResourceManager.GetString("ColumnEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string ColumnExpired {
            get {
                return ResourceManager.GetString("ColumnExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Registration.
        /// </summary>
        internal static string ColumnFirstRegistration {
            get {
                return ResourceManager.GetString("ColumnFirstRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string ColumnGroups {
            get {
                return ResourceManager.GetString("ColumnGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string ColumnInfo {
            get {
                return ResourceManager.GetString("ColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Registration.
        /// </summary>
        internal static string ColumnLastRegistration {
            get {
                return ResourceManager.GetString("ColumnLastRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Name.
        /// </summary>
        internal static string ColumnPackageName {
            get {
                return ResourceManager.GetString("ColumnPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package SID.
        /// </summary>
        internal static string ColumnPackageSid {
            get {
                return ResourceManager.GetString("ColumnPackageSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Push Notification Channel.
        /// </summary>
        internal static string DeleteChannel {
            get {
                return ResourceManager.GetString("DeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this push notification channel?.
        /// </summary>
        internal static string DeleteChannelQuestion {
            get {
                return ResourceManager.GetString("DeleteChannelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Channel....
        /// </summary>
        internal static string NewChannel {
            get {
                return ResourceManager.GetString("NewChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new channel to send push notifications..
        /// </summary>
        internal static string NewChannelDescription {
            get {
                return ResourceManager.GetString("NewChannelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Push Notification Channel.
        /// </summary>
        internal static string NewChannelDialogTitle {
            get {
                return ResourceManager.GetString("NewChannelDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing backup....
        /// </summary>
        internal static string PerformingBackup {
            get {
                return ResourceManager.GetString("PerformingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing restore....
        /// </summary>
        internal static string PerformingRestore {
            get {
                return ResourceManager.GetString("PerformingRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usis Push Notification Router.
        /// </summary>
        internal static string RootNodeDisplayName {
            get {
                return ResourceManager.GetString("RootNodeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Notification....
        /// </summary>
        internal static string SendNotification {
            get {
                return ResourceManager.GetString("SendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a push notification to the selected device..
        /// </summary>
        internal static string SendNotificationDescription {
            get {
                return ResourceManager.GetString("SendNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Expired Devices.
        /// </summary>
        internal static string ShowExpiredDevices {
            get {
                return ResourceManager.GetString("ShowExpiredDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The usis Push Notification Router snap-in allows you to manage channels for sending push notifications to mobile devices..
        /// </summary>
        internal static string SnapInDescription {
            get {
                return ResourceManager.GetString("SnapInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usis Push Notification Router.
        /// </summary>
        internal static string SnapInDisplayName {
            get {
                return ResourceManager.GetString("SnapInDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StartViewDisplayName {
            get {
                return ResourceManager.GetString("StartViewDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string TitleBackup {
            get {
                return ResourceManager.GetString("TitleBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string TitleRestore {
            get {
                return ResourceManager.GetString("TitleRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information Exchange (*.p12)|*.p12.
        /// </summary>
        internal static string UploadCertifiateFilter {
            get {
                return ResourceManager.GetString("UploadCertifiateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WNS.
        /// </summary>
        internal static string WNS {
            get {
                return ResourceManager.GetString("WNS", resourceCulture);
            }
        }
    }
}
