//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usis.Net.Bits.Administration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("usis.Net.Bits.Administration.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File....
        /// </summary>
        internal static string AddFileActionDisplayName {
            get {
                return ResourceManager.GetString("AddFileActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All Jobs....
        /// </summary>
        internal static string CancelAlJobsActionDisplayName {
            get {
                return ResourceManager.GetString("CancelAlJobsActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All Jobs.
        /// </summary>
        internal static string CancelAllJobsDialogCaption {
            get {
                return ResourceManager.GetString("CancelAllJobsDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel all jobs?.
        /// </summary>
        internal static string CancelAllJobsDialogText {
            get {
                return ResourceManager.GetString("CancelAllJobsDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel....
        /// </summary>
        internal static string CancelJobActionDisplayName {
            get {
                return ResourceManager.GetString("CancelJobActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Job.
        /// </summary>
        internal static string CancelJobDialogCaption {
            get {
                return ResourceManager.GetString("CancelJobDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the job &apos;{0}&apos;?.
        /// </summary>
        internal static string CancelJobDialogText {
            get {
                return ResourceManager.GetString("CancelJobDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete....
        /// </summary>
        internal static string CompleteJobActionDisplayName {
            get {
                return ResourceManager.GetString("CompleteJobActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend Job.
        /// </summary>
        internal static string CompleteJobDialogCaption {
            get {
                return ResourceManager.GetString("CompleteJobDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to complete the job &apos;{0}&apos;?.
        /// </summary>
        internal static string CompleteJobDialogText {
            get {
                return ResourceManager.GetString("CompleteJobDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Job....
        /// </summary>
        internal static string CreateJobActionDisplayName {
            get {
                return ResourceManager.GetString("CreateJobActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Name - Download.
        /// </summary>
        internal static string FileDialogDownlaodLocalNameTitle {
            get {
                return ResourceManager.GetString("FileDialogDownlaodLocalNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Name - Upload.
        /// </summary>
        internal static string FIleDialogUploadLocalNameTitle {
            get {
                return ResourceManager.GetString("FIleDialogUploadLocalNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string JobGeneralPropertyPageTitle {
            get {
                return ResourceManager.GetString("JobGeneralPropertyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITS Jobs.
        /// </summary>
        internal static string JobListViewDisplayName {
            get {
                return ResourceManager.GetString("JobListViewDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume....
        /// </summary>
        internal static string ResumeJobActionDisplayName {
            get {
                return ResourceManager.GetString("ResumeJobActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Job.
        /// </summary>
        internal static string ResumeJobDialogCaption {
            get {
                return ResourceManager.GetString("ResumeJobDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to resume the job &apos;{0}&apos;?.
        /// </summary>
        internal static string ResumeJobDialogText {
            get {
                return ResourceManager.GetString("ResumeJobDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITS Jobs.
        /// </summary>
        internal static string RootNodeDisplayName {
            get {
                return ResourceManager.GetString("RootNodeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Jobs of All Users.
        /// </summary>
        internal static string ShowAllJobs {
            get {
                return ResourceManager.GetString("ShowAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend....
        /// </summary>
        internal static string SuspendJobActionDisplayName {
            get {
                return ResourceManager.GetString("SuspendJobActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend Job.
        /// </summary>
        internal static string SuspendJobDialogCaption {
            get {
                return ResourceManager.GetString("SuspendJobDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to suspend the job &apos;{0}&apos;?.
        /// </summary>
        internal static string SuspendJobDialogText {
            get {
                return ResourceManager.GetString("SuspendJobDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Ownership....
        /// </summary>
        internal static string TakeOwnershipJobActionDisplayName {
            get {
                return ResourceManager.GetString("TakeOwnershipJobActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Ownership.
        /// </summary>
        internal static string TakeOwnershipJobDialogCaption {
            get {
                return ResourceManager.GetString("TakeOwnershipJobDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to take the ownership of the job &apos;{0}&apos;?.
        /// </summary>
        internal static string TakeOwnershipJobDialogText {
            get {
                return ResourceManager.GetString("TakeOwnershipJobDialogText", resourceCulture);
            }
        }
    }
}
