//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usis.Finance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Security> Securities { get; set; }
        public virtual DbSet<SecurityDE> SecurityDEs { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
