//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usis.Finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public Security()
        {
            this.Prices = new HashSet<Price>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public System.Guid SecurityId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string ISIN { get; set; }
        public int TradeableUnits { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public string ChangedBy { get; set; }
        public int UpdateCount { get; set; }
        public byte Deleted { get; set; }
    
        public virtual ICollection<Price> Prices { get; set; }
        public virtual SecurityDE SecurityDE { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
