//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usis.Finance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid TransactionId { get; set; }
        public System.Guid PortfolioId { get; set; }
        public System.Guid SecurityId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public string CurrencyISO { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public string ChangedBy { get; set; }
        public int UpdateCount { get; set; }
        public byte Deleted { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
        public virtual Security Security { get; set; }
    }
}
