//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usis.PushNotification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("usis.PushNotification.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1}.
        /// </summary>
        internal static string ArgumentsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup: APNs Channels ....
        /// </summary>
        internal static string BackupApnsChannels {
            get {
                return ResourceManager.GetString("BackupApnsChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup: APNs Receivers ....
        /// </summary>
        internal static string BackupApnsReceivers {
            get {
                return ResourceManager.GetString("BackupApnsReceivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup: Channels ....
        /// </summary>
        internal static string BackupChannels {
            get {
                return ResourceManager.GetString("BackupChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... backup completed..
        /// </summary>
        internal static string BackupComplete {
            get {
                return ResourceManager.GetString("BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup: Notifications ....
        /// </summary>
        internal static string BackupNotifications {
            get {
                return ResourceManager.GetString("BackupNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing backup:.
        /// </summary>
        internal static string BackupPerforming {
            get {
                return ResourceManager.GetString("BackupPerforming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup: Receivers ....
        /// </summary>
        internal static string BackupReceivers {
            get {
                return ResourceManager.GetString("BackupReceivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting backup ....
        /// </summary>
        internal static string BackupStarting {
            get {
                return ResourceManager.GetString("BackupStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup: WNS Channels ....
        /// </summary>
        internal static string BackupWnsChannels {
            get {
                return ResourceManager.GetString("BackupWnsChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup: WNS Receivers ....
        /// </summary>
        internal static string BackupWnsReceivers {
            get {
                return ResourceManager.GetString("BackupWnsReceivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The push notification channel &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ChannelAlreadyExists {
            get {
                return ResourceManager.GetString("ChannelAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The push notification channel &apos;{0} does not exist..
        /// </summary>
        internal static string ChannelDoesNotExist {
            get {
                return ResourceManager.GetString("ChannelDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the push notification channel &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToCreateChannel {
            get {
                return ResourceManager.GetString("FailedToCreateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the notification to the send queue..
        /// </summary>
        internal static string FailedToSaveNotification {
            get {
                return ResourceManager.GetString("FailedToSaveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send notification:.
        /// </summary>
        internal static string FailedToSendNotification {
            get {
                return ResourceManager.GetString("FailedToSendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New receiver registered..
        /// </summary>
        internal static string NewReceiverRegistered {
            get {
                return ResourceManager.GetString("NewReceiverRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no certificate installed for this channel..
        /// </summary>
        internal static string NoCertificateInstalled {
            get {
                return ResourceManager.GetString("NoCertificateInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data source configured..
        /// </summary>
        internal static string NoDataSourceConfigured {
            get {
                return ResourceManager.GetString("NoDataSourceConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification with the specified identifier does not exist..
        /// </summary>
        internal static string NotificationDoesNotExist {
            get {
                return ResourceManager.GetString("NotificationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification was saved to the send queue..
        /// </summary>
        internal static string NotificationSavedToSendQueue {
            get {
                return ResourceManager.GetString("NotificationSavedToSendQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver already registered..
        /// </summary>
        internal static string ReceiverAlreadyRegistered {
            get {
                return ResourceManager.GetString("ReceiverAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receiver &apos;{0}&apos; is not registered..
        /// </summary>
        internal static string ReceiverNotRegistered {
            get {
                return ResourceManager.GetString("ReceiverNotRegistered", resourceCulture);
            }
        }
    }
}
